services:
  postgres:
    image: 'postgres:latest'
    container_name: puzzle-db
    environment:
      - 'POSTGRES_DB=puzzle-photos'
      - 'POSTGRES_PASSWORD=r@@tmaster'
      - 'POSTGRES_USER=postgres'
    ports:
      - '2345:5432'
