spring.datasource.url=jdbc:postgresql://localhost:2345/puzzle-photos
spring.datasource.password=r@@tmaster
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect



spring.datasource.tomcat.connection-properties=useUnicode=true;characterEncoding=utf-8mb4;
spring.jpa.hibernate.ddl-auto = update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
spring.jpa.show-sql=true

spring.application.name=Puzzle

